version: '2'
services:
    schedulerservice-mysql:
        container_name: schedulerservice-mysql
        image: mysql:5.7.15
        # volumes:
        #     - ~/volumes/jhipster/schedulerservice/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=schedulerservice
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
